common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name = 'common'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('', include('farm.urls')),
    #path('', views.index, name='index'),  # '/' 에 해당되는 path
]

farm/urls.py
from django.urls import path

from . import views

app_name ='farm'

urlpatterns = [
    path('farm/<int:user_id>/', views.index, name='index'),
    path('farm/modify/<int:user_id>', views.aduino_modify, name='aduino_modify'),
    path('farm/auto/<int:user_id>', views.aduino_auto, name='aduino_auto'),
    path('farm/insert/<int:user_id>', views.aduino_insert, name='aduino_insert'),
    path('farm/ajax/<int:user_id>',views.ajax_method, name='ajax_method'),
    path('farm/detail/<int:question_id>/', views.detail, name='detail'),
    path('farm/answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('farm/question/create/', views.question_create, name='question_create'),
    
]

farm/models.py
from django.db import models
from common.models import CustomUser

class Aduino(models.Model):
    useridx = models.IntegerField()
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    devicer= models.IntegerField()
    temp = models.IntegerField()
    hum = models.IntegerField()
    illum = models.IntegerField()
    waterCycle= models.IntegerField()
    nowtemp = models.IntegerField()
    nowhum = models.IntegerField()
    nowillum = models.IntegerField()
    nowwaterCycle= models.IntegerField()

class Question(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

farm/forms.py
from django import forms
from .models import Aduino
from .models import Question
from .models import Answer

class AduinoForm(forms.ModelForm):
    class Meta:
        model = Aduino
        fields = ['temp','hum','illum','waterCycle']

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
       
        labels = {
            'subject': '제목',
            'content': '내용',
        }  
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

farm/views.py
from sre_constants import SUCCESS
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render, get_object_or_404, redirect

from .models import Aduino
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from .serializers import AduinoSerializer

from django.utils import timezone
from .models import Question
from .forms import QuestionForm,AnswerForm
from django.core.paginator import Paginator  
from django.contrib.auth.decorators import login_required

from .forms import AduinoForm
from django.http import JsonResponse

def index(request,user_id):
    aduino = get_object_or_404(Aduino, useridx=user_id)
    
    page = request.GET.get('page', '1')  # 페이지
    question_list = Question.objects.order_by('-create_date')
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'aduino':aduino,'question_list': page_obj}
    return render(request, 'farm/dashboard.html', context)

@csrf_exempt
def aduino_modify(request,user_id):
    obj = Aduino.objects.get(useridx=user_id)
    if request.method == "POST": 
        data = JSONParser().parse(request)
        device = data[0].get("device","")
        if(obj.devicer == device):
        #userid = data[0].get("username","")
        #userpw = data[0].get("userpw","")
        #login_result = authenticate(username=userid, password=userpw)
        #print("userid = " + userid + " result = " + str(login_result))
        #if login_result:
            serializer = AduinoSerializer(obj, data = data[1])
            if serializer.is_valid():
                serializer.save()
                return HttpResponse(status=200)

@csrf_exempt
def aduino_auto(request,user_id):
    if request.method == "GET":
        obj = Aduino.objects.get(useridx=user_id)
        data = {
            "temp":obj.temp,    
            "hum":obj.hum,
            "ilum":obj.illum,
            "waterCycle":obj.waterCycle
        }
        return JsonResponse(data)

@csrf_exempt
def ajax_method(request,user_id):
        obj = Aduino.objects.get(useridx=user_id)
        data = {
            "nowtemp":obj.nowtemp,
            "nowhum":obj.nowhum,
            "nowillum":obj.nowillum,
            "nowwaterCycle":obj.nowwaterCycle
           }

        return JsonResponse(data)

def aduino_insert(request,user_id):
    obj = Aduino.objects.get(useridx=user_id)
    if request.method == "POST":
        form = AduinoForm(request.POST)
        if form.is_valid():
            temp = form.cleaned_data.get('temp')
            hum= form.cleaned_data.get('hum')
            illum = form.cleaned_data.get('illum')
            waterCycle = form.cleaned_data.get('waterCycle')
            obj.temp = temp
            obj.hum = hum
            obj.illum = illum
            obj.waterCycle = waterCycle
            obj.save()
            return redirect('farm:index', user_id=user_id)
    else:
        form = AduinoForm()
    return redirect('farm:index', user_id=user_id)

def detail(request,question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'farm/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('farm:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'farm/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('farm:index', user_id=request.user.id)
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'farm/question_form.html', context)

templates/farm/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
{% load filter %}
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
 $.ajax({
        url: "{% url 'farm:ajax_method' user.id %}",
        dataType: "json",
        success: function (data) {
            var ajax="";

            ajax += "<tr class='text-center'>"
            ajax += "<td>" + data.nowtemp + "</td>"
            ajax += "<td>" + data.nowhum + "</td>"
            ajax += "<td>" + data.nowillum + "</td>"
            ajax += "<td>" + data.nowwaterCycle + "</td>"
            ajax += "</tr>"
            $('[id="ajax"]').html(ajax);
        },
        error: function (request, status, error) {
            console.log('실패');
        }
   })	
 setInterval(function (){
  	$.ajax({
        url: "{% url 'farm:ajax_method' user.id %}",
        dataType: "json",
        success: function (data) {
            var ajax="";
            
            ajax += "<tr class='text-center'>"
            ajax += "<td>" + data.nowtemp + "</td>"
            ajax += "<td>" + data.nowhum + "</td>"
            ajax += "<td>" + data.nowillum + "</td>"
            ajax += "<td>" + data.nowwaterCycle + "</td>"
            ajax += "</tr>"
            console.log(data.nowtemp);
            $('[id="ajax"]').html(ajax);
        },
        error: function (request, status, error) {
            console.log('실패');
        }
   });
  },3000);
});
</script>
  <div class="container my-3"  >
    <table class="table" id="here">
        <thead>
            <tr class="text-center table-dark">
                <th>현재 온도</th>
                <th >현재 습도</th>
                <th>현재 조도</th>
                <th>토양 수분</th>
            </tr>
        </thead>
        <tbody id="ajax">
         
        </tbody>
    </table>
 
    <div class="card" style="width: 30%; float:left; margin-right:50px;">
    <form method="post" action="{% url 'farm:aduino_insert' user.id %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="card-header" >원하는 값을 설정하세요</div>
        
        <ul class="list-group list-group-flush">
            <li class="list-group-item"><label for="temp" class="col-sm-6 col-form-label">온도 </label>
            <input type="text" class="form-control" name="temp" id="temp" value="{{ aduino.temp }}"
                   value="{{ form.temp.value|default_if_none:'' }}"></li>

            <li class="list-group-item"><label for="hum"class="col-sm-6 col-form-label">습도</label>
            <input type="text" class="form-control" name="hum" id="hum" value="{{ aduino.hum }}"
                          value="{{ form.hum.value|default_if_none:'' }}"></li>

            <li class="list-group-item"><label for="illum" class="col-sm-6 col-form-label">조도</label>
            <input type="text" class="form-control" name="illum" id="illum" value="{{ aduino.illum }}"
                                 value="{{ form.illum.value|default_if_none:'' }}"></li>

            <li class="list-group-item"><label for="waterCycle"class="col-sm-6 col-form-label">토양 수분</label>
            <input type="text" class="form-control" name="waterCycle" id="waterCycle"  value="{{ aduino.waterCycle }}"
                                        value="{{ form.waterCycle.value|default_if_none:'' }}"></li>
    
        <button type="submit" class="btn btn-primary" style="background-color:black; border-color:black;">저장</button>
      </ul>     
  </form>
  </div>
<div class="card" style="width: 66%; float:left;">
  <form>
	<table class="table">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-start">
                <a href="{% url 'farm:detail' question.id  %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            
            </td>
            <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
      <!-- 페이징처리 시작 -->
      <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'farm:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</form>
</div>
</div>  
</div>
</div>




{% else %}
<head>
    <meta http-equiv="refresh" content="0; {% url 'common:login' %}">
</head>
{% endif %}
{%endblock%}

templates/farm/question_detail.html
{% extends 'base.html' %}
{% block content %}
{% if user.is_authenticated %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'farm:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
                <!-- 오류표시 Start -->
                {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                    {% for field in form %}
                    {% if field.errors %}
                    <div>
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
                <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
    <a class="navbar-brand" href="{% url 'farm:index' user.id%}">돌아가기</a>
</div>
{% else %}
<head>
    <meta http-equiv="refresh" content="0; {% url 'common:login' %}">
</head>
{% endif %}
{% endblock %}

templates/farm/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
        <a class="navbar-brand" href="{% url 'farm:index' user.id%}">돌아가기</a>
    </form>
</div>
{% endblock %}